# Generated by Django 5.0.6 on 2024-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_message', '0002_rename_time_stamp_privatemessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
